"""Shared target definitions for UniGate demo seed generation."""

from __future__ import annotations

from typing import Any


ADDITIONAL_SEED_TARGETS: list[dict[str, str]] = [
    {
        "university_id": "bit-cs",
        "university_name": "Beijing Institute of Technology",
        "country": "China",
        "degree_level": "Masters",
        "program_name": "MS Computer Science",
        "admissions_url": "https://isc.bit.edu.cn/",
    },
    {
        "university_id": "hit-ai",
        "university_name": "Harbin Institute of Technology",
        "country": "China",
        "degree_level": "Masters",
        "program_name": "MS Artificial Intelligence",
        "admissions_url": "https://en.hit.edu.cn/admissions",
    },
    {
        "university_id": "zhejiang-ds",
        "university_name": "Zhejiang University",
        "country": "China",
        "degree_level": "Masters",
        "program_name": "MS Data Science",
        "admissions_url": "https://www.zju.edu.cn/english/",
    },
    {
        "university_id": "ustc-cs",
        "university_name": "University of Science and Technology of China (USTC)",
        "country": "China",
        "degree_level": "Masters",
        "program_name": "MS Computer Science",
        "admissions_url": "https://isa.ustc.edu.cn/",
    },
    {
        "university_id": "tongji-se",
        "university_name": "Tongji University",
        "country": "China",
        "degree_level": "Masters",
        "program_name": "MS Software Engineering",
        "admissions_url": "https://study.tongji.edu.cn/",
    },
    {
        "university_id": "utm-cs",
        "university_name": "Universiti Teknologi Malaysia (UTM)",
        "country": "Malaysia",
        "degree_level": "Masters",
        "program_name": "MS Computer Science",
        "admissions_url": "https://admission.utm.my/",
    },
    {
        "university_id": "um-ds",
        "university_name": "Universiti Malaya (UM)",
        "country": "Malaysia",
        "degree_level": "Masters",
        "program_name": "MS Data Science",
        "admissions_url": "https://study.um.edu.my/",
    },
    {
        "university_id": "apu-ai",
        "university_name": "Asia Pacific University (APU)",
        "country": "Malaysia",
        "degree_level": "Masters",
        "program_name": "MS Artificial Intelligence",
        "admissions_url": "https://www.apu.edu.my/admissions",
    },
    {
        "university_id": "ctu-prague-cs",
        "university_name": "Czech Technical University in Prague",
        "country": "Czech Republic",
        "degree_level": "Masters",
        "program_name": "MS Computer Science",
        "admissions_url": "https://www.cvut.cz/en/degree-programmes",
    },
    {
        "university_id": "charles-prague-ai",
        "university_name": "Charles University Prague",
        "country": "Czech Republic",
        "degree_level": "Masters",
        "program_name": "MS Artificial Intelligence",
        "admissions_url": "https://cuni.cz/UKEN-1.html",
    },
    {
        "university_id": "bme-cs",
        "university_name": "Budapest University of Technology",
        "country": "Hungary",
        "degree_level": "Masters",
        "program_name": "MS Computer Science",
        "admissions_url": "https://www.bme.hu/en/admission",
    },
    {
        "university_id": "elte-ds",
        "university_name": "Eotvos Lorand University (ELTE)",
        "country": "Hungary",
        "degree_level": "Masters",
        "program_name": "MS Data Science",
        "admissions_url": "https://www.elte.hu/en/admissions",
    },
    {
        "university_id": "polimi-cs",
        "university_name": "Politecnico di Milano",
        "country": "Italy",
        "degree_level": "Masters",
        "program_name": "MSc Computer Science",
        "admissions_url": "https://www.polimi.it/en/prospective-students",
    },
    {
        "university_id": "bologna-ai",
        "university_name": "University of Bologna",
        "country": "Italy",
        "degree_level": "Masters",
        "program_name": "MSc Artificial Intelligence",
        "admissions_url": "https://www.unibo.it/en/study",
    },
    {
        "university_id": "sapienza-ds",
        "university_name": "Sapienza University of Rome",
        "country": "Italy",
        "degree_level": "Masters",
        "program_name": "MSc Data Science",
        "admissions_url": "https://www.uniroma1.it/en/pagina-strutturale/home",
    },
    {
        "university_id": "tudelft-cs",
        "university_name": "Delft University of Technology (TU Delft)",
        "country": "Netherlands",
        "degree_level": "Masters",
        "program_name": "MSc Computer Science",
        "admissions_url": "https://www.tudelft.nl/en/education/programmes/masters",
    },
    {
        "university_id": "uva-ai",
        "university_name": "University of Amsterdam",
        "country": "Netherlands",
        "degree_level": "Masters",
        "program_name": "MSc Artificial Intelligence",
        "admissions_url": "https://www.uva.nl/en/education/masters.html",
    },
    {
        "university_id": "tue-ds",
        "university_name": "Eindhoven University of Technology",
        "country": "Netherlands",
        "degree_level": "Masters",
        "program_name": "MSc Data Science",
        "admissions_url": "https://www.tue.nl/en/education/graduate-school",
    },
    {
        "university_id": "kth-cs",
        "university_name": "KTH Royal Institute of Technology",
        "country": "Sweden",
        "degree_level": "Masters",
        "program_name": "MSc Computer Science",
        "admissions_url": "https://www.kth.se/en/studies/master",
    },
    {
        "university_id": "chalmers-ds",
        "university_name": "Chalmers University of Technology",
        "country": "Sweden",
        "degree_level": "Masters",
        "program_name": "MSc Data Science",
        "admissions_url": "https://www.chalmers.se/en/education/your-studies/application-and-admission/",
    },
    {
        "university_id": "uio-cs",
        "university_name": "University of Oslo",
        "country": "Norway",
        "degree_level": "Masters",
        "program_name": "MSc Computer Science",
        "admissions_url": "https://www.uio.no/english/studies/admission/master/",
    },
    {
        "university_id": "ntnu-ai",
        "university_name": "Norwegian University of Science and Technology (NTNU)",
        "country": "Norway",
        "degree_level": "Masters",
        "program_name": "MSc AI",
        "admissions_url": "https://www.ntnu.edu/studies/msai",
    },
    {
        "university_id": "aalto-cs",
        "university_name": "Aalto University",
        "country": "Finland",
        "degree_level": "Masters",
        "program_name": "MSc Computer Science",
        "admissions_url": "https://www.aalto.fi/en/study-options",
    },
    {
        "university_id": "helsinki-ds",
        "university_name": "University of Helsinki",
        "country": "Finland",
        "degree_level": "Masters",
        "program_name": "MSc Data Science",
        "admissions_url": "https://www.helsinki.fi/en/admissions-and-education",
    },
    {
        "university_id": "tuwien-cs",
        "university_name": "Vienna University of Technology (TU Wien)",
        "country": "Austria",
        "degree_level": "Masters",
        "program_name": "MSc Computer Science",
        "admissions_url": "https://www.tuwien.at/en/studies/admission",
    },
    {
        "university_id": "upm-ai",
        "university_name": "Universidad Politecnica de Madrid",
        "country": "Spain",
        "degree_level": "Masters",
        "program_name": "MSc Artificial Intelligence",
        "admissions_url": "https://www.upm.es/internacional",
    },
    {
        "university_id": "barcelona-ds",
        "university_name": "University of Barcelona",
        "country": "Spain",
        "degree_level": "Masters",
        "program_name": "MSc Data Science",
        "admissions_url": "https://www.ub.edu/web/ub/en/studies/official_master_s_degree/welcome.html",
    },
    {
        "university_id": "mit-cs-phd",
        "university_name": "MIT",
        "country": "USA",
        "degree_level": "PhD",
        "program_name": "PhD Computer Science",
        "admissions_url": "https://www.eecs.mit.edu/academics/graduate-programs/",
    },
    {
        "university_id": "stanford-ai-phd",
        "university_name": "Stanford University",
        "country": "USA",
        "degree_level": "PhD",
        "program_name": "PhD Artificial Intelligence",
        "admissions_url": "https://cs.stanford.edu/admissions/graduate-admissions",
    },
    {
        "university_id": "cmu-ml",
        "university_name": "Carnegie Mellon University",
        "country": "USA",
        "degree_level": "Masters",
        "program_name": "MS Machine Learning",
        "admissions_url": "https://www.cmu.edu/scs/admissions/masters/",
    },
    {
        "university_id": "melbourne-cs",
        "university_name": "University of Melbourne",
        "country": "Australia",
        "degree_level": "Masters",
        "program_name": "MS Computer Science",
        "admissions_url": "https://study.unimelb.edu.au/find/courses/graduate/master-of-computer-science/",
    },
    {
        "university_id": "sydney-ds",
        "university_name": "University of Sydney",
        "country": "Australia",
        "degree_level": "Masters",
        "program_name": "MS Data Science",
        "admissions_url": "https://www.sydney.edu.au/courses/courses/pc/master-of-data-science.html",
    },
    {
        "university_id": "anu-ai",
        "university_name": "Australian National University (ANU)",
        "country": "Australia",
        "degree_level": "Masters",
        "program_name": "MS AI",
        "admissions_url": "https://www.anu.edu.au/study/apply",
    },
    {
        "university_id": "auckland-cs",
        "university_name": "University of Auckland",
        "country": "New Zealand",
        "degree_level": "Masters",
        "program_name": "MS Computer Science",
        "admissions_url": "https://www.auckland.ac.nz/en/study/study-options/find-a-study-option/master-of-science.html",
    },
    {
        "university_id": "kaist-cs",
        "university_name": "KAIST",
        "country": "South Korea",
        "degree_level": "Masters",
        "program_name": "MS Computer Science",
        "admissions_url": "https://admission.kaist.ac.kr/intl-graduate/",
    },
    {
        "university_id": "snu-ai",
        "university_name": "Seoul National University",
        "country": "South Korea",
        "degree_level": "Masters",
        "program_name": "MS AI",
        "admissions_url": "https://admission.snu.ac.kr/graduate",
    },
    {
        "university_id": "postech-ds",
        "university_name": "POSTECH",
        "country": "South Korea",
        "degree_level": "Masters",
        "program_name": "MS Data Science",
        "admissions_url": "https://admission.postech.ac.kr/graduate/",
    },
    {
        "university_id": "tokyo-cs",
        "university_name": "University of Tokyo",
        "country": "Japan",
        "degree_level": "Masters",
        "program_name": "MS Computer Science",
        "admissions_url": "https://www.u-tokyo.ac.jp/en/prospective-students/graduate.html",
    },
    {
        "university_id": "osaka-ai",
        "university_name": "Osaka University",
        "country": "Japan",
        "degree_level": "Masters",
        "program_name": "MS AI",
        "admissions_url": "https://www.osaka-u.ac.jp/en/admissions/graduate",
    },
    {
        "university_id": "nus-cs",
        "university_name": "National University of Singapore (NUS)",
        "country": "Singapore",
        "degree_level": "Masters",
        "program_name": "MS Computer Science",
        "admissions_url": "https://www.comp.nus.edu.sg/programmes/pg/",
    },
    {
        "university_id": "ntu-ai",
        "university_name": "Nanyang Technological University (NTU)",
        "country": "Singapore",
        "degree_level": "Masters",
        "program_name": "MS AI",
        "admissions_url": "https://www.ntu.edu.sg/admissions/graduate",
    },
]


COUNTRY_FALLBACK_RULES: dict[str, dict[str, Any]] = {
    "China": {
        "application_deadline_start": "2026-03-01",
        "application_deadline_end": "2026-06-30",
        "application_fee_required": False,
        "application_fee_amount": 0,
        "application_fee_currency": "CNY",
        "scholarship_available": True,
        "scholarship_details": "Chinese Government Scholarship and university scholarships may be available for outstanding international students.",
    },
    "Malaysia": {
        "application_deadline_start": "2026-04-01",
        "application_deadline_end": "2026-08-31",
        "application_fee_required": True,
        "application_fee_amount": 200,
        "application_fee_currency": "MYR",
        "scholarship_available": True,
        "scholarship_details": "Merit scholarships and partial tuition waivers are commonly offered for strong applicants.",
    },
    "Czech Republic": {
        "application_deadline_start": "2026-01-15",
        "application_deadline_end": "2026-04-30",
        "application_fee_required": False,
        "application_fee_amount": 0,
        "application_fee_currency": "CZK",
        "scholarship_available": False,
        "scholarship_details": None,
    },
    "Hungary": {
        "application_deadline_start": "2026-01-15",
        "application_deadline_end": "2026-03-31",
        "application_fee_required": True,
        "application_fee_amount": 75,
        "application_fee_currency": "EUR",
        "scholarship_available": True,
        "scholarship_details": "Stipendium Hungaricum and university scholarships are widely available for international students.",
    },
    "Italy": {
        "application_deadline_start": "2026-03-01",
        "application_deadline_end": "2026-07-31",
        "application_fee_required": False,
        "application_fee_amount": 0,
        "application_fee_currency": "EUR",
        "scholarship_available": True,
        "scholarship_details": "Need-based tuition reductions, regional scholarships, and merit awards may be available.",
    },
    "Netherlands": {
        "application_deadline_start": "2026-01-15",
        "application_deadline_end": "2026-04-15",
        "application_fee_required": True,
        "application_fee_amount": 100,
        "application_fee_currency": "EUR",
        "scholarship_available": True,
        "scholarship_details": "Some universities offer merit scholarships and tuition waivers for top international candidates.",
    },
    "Sweden": {
        "application_deadline_start": "2026-10-01",
        "application_deadline_end": "2027-01-15",
        "application_fee_required": True,
        "application_fee_amount": 900,
        "application_fee_currency": "SEK",
        "scholarship_available": True,
        "scholarship_details": "Swedish Institute and university scholarships are common for outstanding international students.",
    },
    "Norway": {
        "application_deadline_start": "2026-12-01",
        "application_deadline_end": "2027-03-01",
        "application_fee_required": False,
        "application_fee_amount": 0,
        "application_fee_currency": "NOK",
        "scholarship_available": False,
        "scholarship_details": None,
    },
    "Finland": {
        "application_deadline_start": "2026-12-01",
        "application_deadline_end": "2027-01-15",
        "application_fee_required": True,
        "application_fee_amount": 100,
        "application_fee_currency": "EUR",
        "scholarship_available": True,
        "scholarship_details": "Fee waivers and scholarship packages are often available for excellent applicants.",
    },
    "Austria": {
        "application_deadline_start": "2026-03-01",
        "application_deadline_end": "2026-05-31",
        "application_fee_required": False,
        "application_fee_amount": 0,
        "application_fee_currency": "EUR",
        "scholarship_available": False,
        "scholarship_details": None,
    },
    "Spain": {
        "application_deadline_start": "2026-04-01",
        "application_deadline_end": "2026-06-30",
        "application_fee_required": True,
        "application_fee_amount": 60,
        "application_fee_currency": "EUR",
        "scholarship_available": False,
        "scholarship_details": None,
    },
    "USA": {
        "application_deadline_start": "2026-09-01",
        "application_deadline_end": "2026-12-15",
        "application_fee_required": True,
        "application_fee_amount": 100,
        "application_fee_currency": "USD",
        "scholarship_available": True,
        "scholarship_details": "PhD and strong master's applicants may receive funding, fellowships, or assistantships.",
    },
    "Australia": {
        "application_deadline_start": "2026-02-01",
        "application_deadline_end": "2026-10-31",
        "application_fee_required": True,
        "application_fee_amount": 125,
        "application_fee_currency": "AUD",
        "scholarship_available": True,
        "scholarship_details": "Merit scholarships and research stipends are common for strong applicants.",
    },
    "New Zealand": {
        "application_deadline_start": "2026-07-01",
        "application_deadline_end": "2026-11-30",
        "application_fee_required": True,
        "application_fee_amount": 50,
        "application_fee_currency": "NZD",
        "scholarship_available": True,
        "scholarship_details": "University scholarships and tuition awards may be offered to international students.",
    },
    "South Korea": {
        "application_deadline_start": "2026-02-01",
        "application_deadline_end": "2026-04-30",
        "application_fee_required": True,
        "application_fee_amount": 100000,
        "application_fee_currency": "KRW",
        "scholarship_available": True,
        "scholarship_details": "KAIST-style tuition waivers and graduate scholarships are common at research universities.",
    },
    "Japan": {
        "application_deadline_start": "2026-11-01",
        "application_deadline_end": "2027-02-28",
        "application_fee_required": True,
        "application_fee_amount": 30000,
        "application_fee_currency": "JPY",
        "scholarship_available": True,
        "scholarship_details": "MEXT-style scholarships, university fee waivers, and lab funding may be available.",
    },
    "Singapore": {
        "application_deadline_start": "2026-08-01",
        "application_deadline_end": "2026-11-30",
        "application_fee_required": True,
        "application_fee_amount": 50,
        "application_fee_currency": "SGD",
        "scholarship_available": True,
        "scholarship_details": "Research scholarships and tuition grants are often available for outstanding graduate applicants.",
    },
}
