"""Shared target definitions for UniGate demo seed generation."""

from __future__ import annotations

from typing import Any


ADDITIONAL_SEED_TARGETS: list[dict[str, str]] = [
    {
        "university_id": "bit-cs",
        "university_name": "Beijing Institute of Technology",
        "country": "China",
        "degree_level": "Masters",
        "program_name": "MS Computer Science",
        "admissions_url": "https://isc.bit.edu.cn/",
    },
    {
        "university_id": "hit-ai",
        "university_name": "Harbin Institute of Technology",
        "country": "China",
        "degree_level": "Masters",
        "program_name": "MS Artificial Intelligence",
        "admissions_url": "https://en.hit.edu.cn/admissions",
    },
    {
        "university_id": "zhejiang-ds",
        "university_name": "Zhejiang University",
        "country": "China",
        "degree_level": "Masters",
        "program_name": "MS Data Science",
        "admissions_url": "https://www.zju.edu.cn/english/",
    },
    {
        "university_id": "ustc-cs",
        "university_name": "University of Science and Technology of China (USTC)",
        "country": "China",
        "degree_level": "Masters",
        "program_name": "MS Computer Science",
        "admissions_url": "https://isa.ustc.edu.cn/",
    },
    {
        "university_id": "tongji-se",
        "university_name": "Tongji University",
        "country": "China",
        "degree_level": "Masters",
        "program_name": "MS Software Engineering",
        "admissions_url": "https://study.tongji.edu.cn/",
    },
    {
        "university_id": "utm-cs",
        "university_name": "Universiti Teknologi Malaysia (UTM)",
        "country": "Malaysia",
        "degree_level": "Masters",
        "program_name": "MS Computer Science",
        "admissions_url": "https://admission.utm.my/",
    },
    {
        "university_id": "um-ds",
        "university_name": "Universiti Malaya (UM)",
        "country": "Malaysia",
        "degree_level": "Masters",
        "program_name": "MS Data Science",
        "admissions_url": "https://study.um.edu.my/",
    },
    {
        "university_id": "apu-ai",
        "university_name": "Asia Pacific University (APU)",
        "country": "Malaysia",
        "degree_level": "Masters",
        "program_name": "MS Artificial Intelligence",
        "admissions_url": "https://www.apu.edu.my/admissions",
    },
    {
        "university_id": "ctu-prague-cs",
        "university_name": "Czech Technical University in Prague",
        "country": "Czech Republic",
        "degree_level": "Masters",
        "program_name": "MS Computer Science",
        "admissions_url": "https://www.cvut.cz/en/degree-programmes",
    },
    {
        "university_id": "charles-prague-ai",
        "university_name": "Charles University Prague",
        "country": "Czech Republic",
        "degree_level": "Masters",
        "program_name": "MS Artificial Intelligence",
        "admissions_url": "https://cuni.cz/UKEN-1.html",
    },
    {
        "university_id": "bme-cs",
        "university_name": "Budapest University of Technology",
        "country": "Hungary",
        "degree_level": "Masters",
        "program_name": "MS Computer Science",
        "admissions_url": "https://www.bme.hu/en/admission",
    },
    {
        "university_id": "elte-ds",
        "university_name": "Eotvos Lorand University (ELTE)",
        "country": "Hungary",
        "degree_level": "Masters",
        "program_name": "MS Data Science",
        "admissions_url": "https://www.elte.hu/en/admissions",
    },
    {
        "university_id": "polimi-cs",
        "university_name": "Politecnico di Milano",
        "country": "Italy",
        "degree_level": "Masters",
        "program_name": "MSc Computer Science",
        "admissions_url": "https://www.polimi.it/en/prospective-students",
    },
    {
        "university_id": "bologna-ai",
        "university_name": "University of Bologna",
        "country": "Italy",
        "degree_level": "Masters",
        "program_name": "MSc Artificial Intelligence",
        "admissions_url": "https://www.unibo.it/en/study",
    },
    {
        "university_id": "sapienza-ds",
        "university_name": "Sapienza University of Rome",
        "country": "Italy",
        "degree_level": "Masters",
        "program_name": "MSc Data Science",
        "admissions_url": "https://www.uniroma1.it/en/pagina-strutturale/home",
    },
    {
        "university_id": "tudelft-cs",
        "university_name": "Delft University of Technology (TU Delft)",
        "country": "Netherlands",
        "degree_level": "Masters",
        "program_name": "MSc Computer Science",
        "admissions_url": "https://www.tudelft.nl/en/education/programmes/masters",
    },
    {
        "university_id": "uva-ai",
        "university_name": "University of Amsterdam",
        "country": "Netherlands",
        "degree_level": "Masters",
        "program_name": "MSc Artificial Intelligence",
        "admissions_url": "https://www.uva.nl/en/education/masters.html",
    },
    {
        "university_id": "tue-ds",
        "university_name": "Eindhoven University of Technology",
        "country": "Netherlands",
        "degree_level": "Masters",
        "program_name": "MSc Data Science",
        "admissions_url": "https://www.tue.nl/en/education/graduate-school",
    },
    {
        "university_id": "kth-cs",
        "university_name": "KTH Royal Institute of Technology",
        "country": "Sweden",
        "degree_level": "Masters",
        "program_name": "MSc Computer Science",
        "admissions_url": "https://www.kth.se/en/studies/master",
    },
    {
        "university_id": "chalmers-ds",
        "university_name": "Chalmers University of Technology",
        "country": "Sweden",
        "degree_level": "Masters",
        "program_name": "MSc Data Science",
        "admissions_url": "https://www.chalmers.se/en/education/your-studies/application-and-admission/",
    },
    {
        "university_id": "uio-cs",
        "university_name": "University of Oslo",
        "country": "Norway",
        "degree_level": "Masters",
        "program_name": "MSc Computer Science",
        "admissions_url": "https://www.uio.no/english/studies/admission/master/",
    },
    {
        "university_id": "ntnu-ai",
        "university_name": "Norwegian University of Science and Technology (NTNU)",
        "country": "Norway",
        "degree_level": "Masters",
        "program_name": "MSc AI",
        "admissions_url": "https://www.ntnu.edu/studies/msai",
    },
    {
        "university_id": "aalto-cs",
        "university_name": "Aalto University",
        "country": "Finland",
        "degree_level": "Masters",
        "program_name": "MSc Computer Science",
        "admissions_url": "https://www.aalto.fi/en/study-options",
    },
    {
        "university_id": "helsinki-ds",
        "university_name": "University of Helsinki",
        "country": "Finland",
        "degree_level": "Masters",
        "program_name": "MSc Data Science",
        "admissions_url": "https://www.helsinki.fi/en/admissions-and-education",
    },
    {
        "university_id": "tuwien-cs",
        "university_name": "Vienna University of Technology (TU Wien)",
        "country": "Austria",
        "degree_level": "Masters",
        "program_name": "MSc Computer Science",
        "admissions_url": "https://www.tuwien.at/en/studies/admission",
    },
    {
        "university_id": "upm-ai",
        "university_name": "Universidad Politecnica de Madrid",
        "country": "Spain",
        "degree_level": "Masters",
        "program_name": "MSc Artificial Intelligence",
        "admissions_url": "https://www.upm.es/internacional",
    },
    {
        "university_id": "barcelona-ds",
        "university_name": "University of Barcelona",
        "country": "Spain",
        "degree_level": "Masters",
        "program_name": "MSc Data Science",
        "admissions_url": "https://www.ub.edu/web/ub/en/studies/official_master_s_degree/welcome.html",
    },
    {
        "university_id": "mit-cs-phd",
        "university_name": "MIT",
        "country": "USA",
        "degree_level": "PhD",
        "program_name": "PhD Computer Science",
        "admissions_url": "https://www.eecs.mit.edu/academics/graduate-programs/",
    },
    {
        "university_id": "stanford-ai-phd",
        "university_name": "Stanford University",
        "country": "USA",
        "degree_level": "PhD",
        "program_name": "PhD Artificial Intelligence",
        "admissions_url": "https://cs.stanford.edu/admissions/graduate-admissions",
    },
    {
        "university_id": "cmu-ml",
        "university_name": "Carnegie Mellon University",
        "country": "USA",
        "degree_level": "Masters",
        "program_name": "MS Machine Learning",
        "admissions_url": "https://www.cmu.edu/scs/admissions/masters/",
    },
    {
        "university_id": "melbourne-cs",
        "university_name": "University of Melbourne",
        "country": "Australia",
        "degree_level": "Masters",
        "program_name": "MS Computer Science",
        "admissions_url": "https://study.unimelb.edu.au/find/courses/graduate/master-of-computer-science/",
    },
    {
        "university_id": "sydney-ds",
        "university_name": "University of Sydney",
        "country": "Australia",
        "degree_level": "Masters",
        "program_name": "MS Data Science",
        "admissions_url": "https://www.sydney.edu.au/courses/courses/pc/master-of-data-science.html",
    },
    {
        "university_id": "anu-ai",
        "university_name": "Australian National University (ANU)",
        "country": "Australia",
        "degree_level": "Masters",
        "program_name": "MS AI",
        "admissions_url": "https://www.anu.edu.au/study/apply",
    },
    {
        "university_id": "auckland-cs",
        "university_name": "University of Auckland",
        "country": "New Zealand",
        "degree_level": "Masters",
        "program_name": "MS Computer Science",
        "admissions_url": "https://www.auckland.ac.nz/en/study/study-options/find-a-study-option/master-of-science.html",
    },
    {
        "university_id": "kaist-cs",
        "university_name": "KAIST",
        "country": "South Korea",
        "degree_level": "Masters",
        "program_name": "MS Computer Science",
        "admissions_url": "https://admission.kaist.ac.kr/intl-graduate/",
    },
    {
        "university_id": "snu-ai",
        "university_name": "Seoul National University",
        "country": "South Korea",
        "degree_level": "Masters",
        "program_name": "MS AI",
        "admissions_url": "https://admission.snu.ac.kr/graduate",
    },
    {
        "university_id": "postech-ds",
        "university_name": "POSTECH",
        "country": "South Korea",
        "degree_level": "Masters",
        "program_name": "MS Data Science",
        "admissions_url": "https://admission.postech.ac.kr/graduate/",
    },
    {
        "university_id": "tokyo-cs",
        "university_name": "University of Tokyo",
        "country": "Japan",
        "degree_level": "Masters",
        "program_name": "MS Computer Science",
        "admissions_url": "https://www.u-tokyo.ac.jp/en/prospective-students/graduate.html",
    },
    {
        "university_id": "osaka-ai",
        "university_name": "Osaka University",
        "country": "Japan",
        "degree_level": "Masters",
        "program_name": "MS AI",
        "admissions_url": "https://www.osaka-u.ac.jp/en/admissions/graduate",
    },
    {
        "university_id": "nus-cs",
        "university_name": "National University of Singapore (NUS)",
        "country": "Singapore",
        "degree_level": "Masters",
        "program_name": "MS Computer Science",
        "admissions_url": "https://www.comp.nus.edu.sg/programmes/pg/",
    },
    {
        "university_id": "ntu-ai",
        "university_name": "Nanyang Technological University (NTU)",
        "country": "Singapore",
        "degree_level": "Masters",
        "program_name": "MS AI",
        "admissions_url": "https://www.ntu.edu.sg/admissions/graduate",
    },
]


MORE_SEED_TARGETS: list[dict[str, str]] = [
    # Portugal
    {
        "university_id": "ist-lisbon-cs-msc",
        "university_name": "Instituto Superior Tecnico (IST) Lisbon",
        "country": "Portugal",
        "degree_level": "Masters",
        "program_name": "MSc Computer Science",
        "admissions_url": "https://tecnico.ulisboa.pt/en/education/",
    },
    {
        "university_id": "ist-lisbon-cs-phd",
        "university_name": "Instituto Superior Tecnico (IST) Lisbon",
        "country": "Portugal",
        "degree_level": "PhD",
        "program_name": "PhD Computer Science",
        "admissions_url": "https://tecnico.ulisboa.pt/en/education/doctorates/",
    },
    {
        "university_id": "porto-ds-msc",
        "university_name": "University of Porto",
        "country": "Portugal",
        "degree_level": "Masters",
        "program_name": "MSc Data Science",
        "admissions_url": "https://sigarra.up.pt/up/en/web_base.gera_pagina?p_pagina=home",
    },
    # Belgium
    {
        "university_id": "ku-leuven-ai-msc",
        "university_name": "KU Leuven",
        "country": "Belgium",
        "degree_level": "Masters",
        "program_name": "MSc AI",
        "admissions_url": "https://www.kuleuven.be/english/study",
    },
    {
        "university_id": "ku-leuven-cs-phd",
        "university_name": "KU Leuven",
        "country": "Belgium",
        "degree_level": "PhD",
        "program_name": "PhD Computer Science",
        "admissions_url": "https://www.kuleuven.be/english/research/phd",
    },
    {
        "university_id": "vub-cs-msc",
        "university_name": "Vrije Universiteit Brussel",
        "country": "Belgium",
        "degree_level": "Masters",
        "program_name": "MSc Computer Science",
        "admissions_url": "https://www.vub.be/en/study",
    },
    # Switzerland
    {
        "university_id": "eth-zurich-cs-bsc",
        "university_name": "ETH Zurich",
        "country": "Switzerland",
        "degree_level": "Bachelors",
        "program_name": "BSc Computer Science",
        "admissions_url": "https://ethz.ch/en/studies/bachelor.html",
    },
    {
        "university_id": "eth-zurich-cs-msc",
        "university_name": "ETH Zurich",
        "country": "Switzerland",
        "degree_level": "Masters",
        "program_name": "MSc Computer Science",
        "admissions_url": "https://ethz.ch/en/studies/master.html",
    },
    {
        "university_id": "eth-zurich-ds-msc",
        "university_name": "ETH Zurich",
        "country": "Switzerland",
        "degree_level": "Masters",
        "program_name": "MSc Data Science",
        "admissions_url": "https://ethz.ch/en/studies/master.html",
    },
    {
        "university_id": "eth-zurich-cs-phd",
        "university_name": "ETH Zurich",
        "country": "Switzerland",
        "degree_level": "PhD",
        "program_name": "PhD Computer Science",
        "admissions_url": "https://ethz.ch/en/studies/doctoral-studies.html",
    },
    {
        "university_id": "epfl-cs-bsc",
        "university_name": "EPFL",
        "country": "Switzerland",
        "degree_level": "Bachelors",
        "program_name": "BSc Computer Science",
        "admissions_url": "https://www.epfl.ch/education/bachelor/",
    },
    {
        "university_id": "epfl-cs-msc",
        "university_name": "EPFL",
        "country": "Switzerland",
        "degree_level": "Masters",
        "program_name": "MSc Computer Science",
        "admissions_url": "https://www.epfl.ch/education/master/",
    },
    {
        "university_id": "epfl-ai-msc",
        "university_name": "EPFL",
        "country": "Switzerland",
        "degree_level": "Masters",
        "program_name": "MSc AI",
        "admissions_url": "https://www.epfl.ch/education/master/",
    },
    {
        "university_id": "epfl-ai-phd",
        "university_name": "EPFL",
        "country": "Switzerland",
        "degree_level": "PhD",
        "program_name": "PhD AI",
        "admissions_url": "https://www.epfl.ch/education/phd/",
    },
    # Denmark
    {
        "university_id": "dtu-cs-msc",
        "university_name": "Technical University of Denmark (DTU)",
        "country": "Denmark",
        "degree_level": "Masters",
        "program_name": "MSc Computer Science",
        "admissions_url": "https://www.dtu.dk/english/education/graduate",
    },
    {
        "university_id": "dtu-ai-msc",
        "university_name": "Technical University of Denmark (DTU)",
        "country": "Denmark",
        "degree_level": "Masters",
        "program_name": "MSc AI",
        "admissions_url": "https://www.dtu.dk/english/education/graduate",
    },
    {
        "university_id": "copenhagen-cs-msc",
        "university_name": "University of Copenhagen",
        "country": "Denmark",
        "degree_level": "Masters",
        "program_name": "MSc Computer Science",
        "admissions_url": "https://studies.ku.dk/masters/",
    },
    # Ireland
    {
        "university_id": "trinity-dublin-cs-msc",
        "university_name": "Trinity College Dublin",
        "country": "Ireland",
        "degree_level": "Masters",
        "program_name": "MSc Computer Science",
        "admissions_url": "https://www.tcd.ie/courses/postgraduate/",
    },
    {
        "university_id": "trinity-dublin-ai-msc",
        "university_name": "Trinity College Dublin",
        "country": "Ireland",
        "degree_level": "Masters",
        "program_name": "MSc AI",
        "admissions_url": "https://www.tcd.ie/courses/postgraduate/",
    },
    {
        "university_id": "ucd-ds-msc",
        "university_name": "University College Dublin (UCD)",
        "country": "Ireland",
        "degree_level": "Masters",
        "program_name": "MSc Data Science",
        "admissions_url": "https://www.ucd.ie/apply/",
    },
    # Poland
    {
        "university_id": "warsaw-tech-cs-msc",
        "university_name": "Warsaw University of Technology",
        "country": "Poland",
        "degree_level": "Masters",
        "program_name": "MSc Computer Science",
        "admissions_url": "https://www.pw.edu.pl/engpw/Studies",
    },
    {
        "university_id": "agh-ai-msc",
        "university_name": "AGH University of Science and Technology",
        "country": "Poland",
        "degree_level": "Masters",
        "program_name": "MSc AI",
        "admissions_url": "https://www.agh.edu.pl/en/studies",
    },
    # Greece
    {
        "university_id": "ntua-cs-msc",
        "university_name": "National Technical University of Athens",
        "country": "Greece",
        "degree_level": "Masters",
        "program_name": "MSc Computer Science",
        "admissions_url": "https://www.ntua.gr/en/studies/",
    },
    {
        "university_id": "auth-ai-msc",
        "university_name": "Aristotle University of Thessaloniki",
        "country": "Greece",
        "degree_level": "Masters",
        "program_name": "MSc AI",
        "admissions_url": "https://www.auth.gr/en/studies/",
    },
    # Estonia
    {
        "university_id": "tartu-cs-msc",
        "university_name": "University of Tartu",
        "country": "Estonia",
        "degree_level": "Masters",
        "program_name": "MSc Computer Science",
        "admissions_url": "https://ut.ee/en/studies/degree-programmes",
    },
    {
        "university_id": "tallinn-tech-ds-msc",
        "university_name": "Tallinn University of Technology",
        "country": "Estonia",
        "degree_level": "Masters",
        "program_name": "MSc Data Science",
        "admissions_url": "https://www.taltech.ee/en/studies",
    },
    # Latvia and Lithuania
    {
        "university_id": "riga-tech-cs-msc",
        "university_name": "Riga Technical University",
        "country": "Latvia",
        "degree_level": "Masters",
        "program_name": "MSc Computer Science",
        "admissions_url": "https://www.rtu.lv/en/studies",
    },
    {
        "university_id": "vilnius-ds-msc",
        "university_name": "Vilnius University",
        "country": "Lithuania",
        "degree_level": "Masters",
        "program_name": "MSc Data Science",
        "admissions_url": "https://www.vu.lt/en/studies",
    },
    # Romania
    {
        "university_id": "cluj-napoca-cs-msc",
        "university_name": "Technical University of Cluj-Napoca",
        "country": "Romania",
        "degree_level": "Masters",
        "program_name": "MSc Computer Science",
        "admissions_url": "https://www.utcluj.ro/en/education/",
    },
    {
        "university_id": "politehnica-bucharest-ai-msc",
        "university_name": "University Politehnica of Bucharest",
        "country": "Romania",
        "degree_level": "Masters",
        "program_name": "MSc AI",
        "admissions_url": "https://upb.ro/en/",
    },
    # Serbia, Croatia, Slovakia
    {
        "university_id": "belgrade-cs-msc",
        "university_name": "University of Belgrade",
        "country": "Serbia",
        "degree_level": "Masters",
        "program_name": "MSc Computer Science",
        "admissions_url": "https://www.bg.ac.rs/en/",
    },
    {
        "university_id": "zagreb-cs-msc",
        "university_name": "University of Zagreb",
        "country": "Croatia",
        "degree_level": "Masters",
        "program_name": "MSc Computer Science",
        "admissions_url": "https://www.unizg.hr/homepage/",
    },
    {
        "university_id": "slovak-tech-cs-msc",
        "university_name": "Slovak University of Technology",
        "country": "Slovakia",
        "degree_level": "Masters",
        "program_name": "MSc Computer Science",
        "admissions_url": "https://www.stuba.sk/english.html",
    },
    # Additional Germany
    {
        "university_id": "lmu-munich-ds-msc",
        "university_name": "Ludwig Maximilian University Munich",
        "country": "Germany",
        "degree_level": "Masters",
        "program_name": "MSc Data Science",
        "admissions_url": "https://www.en.uni-muenchen.de/students/application/index.html",
    },
    {
        "university_id": "lmu-munich-ai-msc",
        "university_name": "Ludwig Maximilian University Munich",
        "country": "Germany",
        "degree_level": "Masters",
        "program_name": "MSc AI",
        "admissions_url": "https://www.en.uni-muenchen.de/students/application/index.html",
    },
    {
        "university_id": "heidelberg-ds-msc",
        "university_name": "Heidelberg University",
        "country": "Germany",
        "degree_level": "Masters",
        "program_name": "MSc Data Science",
        "admissions_url": "https://www.uni-heidelberg.de/en/study",
    },
    {
        "university_id": "stuttgart-cs-msc",
        "university_name": "University of Stuttgart",
        "country": "Germany",
        "degree_level": "Masters",
        "program_name": "MSc Computer Science",
        "admissions_url": "https://www.uni-stuttgart.de/en/study/",
    },
    {
        "university_id": "freiburg-cs-msc",
        "university_name": "University of Freiburg",
        "country": "Germany",
        "degree_level": "Masters",
        "program_name": "MSc Computer Science",
        "admissions_url": "https://www.uni-freiburg.de/en/study",
    },
    {
        "university_id": "bonn-cs-msc",
        "university_name": "University of Bonn",
        "country": "Germany",
        "degree_level": "Masters",
        "program_name": "MSc Computer Science",
        "admissions_url": "https://www.uni-bonn.de/en/studying",
    },
    {
        "university_id": "bonn-ai-msc",
        "university_name": "University of Bonn",
        "country": "Germany",
        "degree_level": "Masters",
        "program_name": "MSc AI",
        "admissions_url": "https://www.uni-bonn.de/en/studying",
    },
    {
        "university_id": "fu-berlin-cs-msc",
        "university_name": "Free University Berlin",
        "country": "Germany",
        "degree_level": "Masters",
        "program_name": "MSc Computer Science",
        "admissions_url": "https://www.fu-berlin.de/en/studium/index.html",
    },
    {
        "university_id": "hamburg-ias-msc",
        "university_name": "University of Hamburg",
        "country": "Germany",
        "degree_level": "Masters",
        "program_name": "MSc Intelligent Adaptive Systems",
        "admissions_url": "https://www.uni-hamburg.de/en/studium.html",
    },
    # Additional UK
    {
        "university_id": "edinburgh-ai-msc",
        "university_name": "University of Edinburgh",
        "country": "UK",
        "degree_level": "Masters",
        "program_name": "MSc AI",
        "admissions_url": "https://www.ed.ac.uk/studying/postgraduate/degrees",
    },
    {
        "university_id": "edinburgh-ds-msc",
        "university_name": "University of Edinburgh",
        "country": "UK",
        "degree_level": "Masters",
        "program_name": "MSc Data Science",
        "admissions_url": "https://www.ed.ac.uk/studying/postgraduate/degrees",
    },
    {
        "university_id": "edinburgh-ai-phd",
        "university_name": "University of Edinburgh",
        "country": "UK",
        "degree_level": "PhD",
        "program_name": "PhD AI",
        "admissions_url": "https://www.ed.ac.uk/studying/postgraduate/research",
    },
    {
        "university_id": "ucl-cs-bsc",
        "university_name": "University College London (UCL)",
        "country": "UK",
        "degree_level": "Bachelors",
        "program_name": "BSc Computer Science",
        "admissions_url": "https://www.ucl.ac.uk/prospective-students/undergraduate",
    },
    {
        "university_id": "ucl-cs-msc",
        "university_name": "University College London (UCL)",
        "country": "UK",
        "degree_level": "Masters",
        "program_name": "MSc Computer Science",
        "admissions_url": "https://www.ucl.ac.uk/prospective-students/graduate/taught-degrees",
    },
    {
        "university_id": "ucl-ai-msc",
        "university_name": "University College London (UCL)",
        "country": "UK",
        "degree_level": "Masters",
        "program_name": "MSc AI",
        "admissions_url": "https://www.ucl.ac.uk/prospective-students/graduate/taught-degrees",
    },
    {
        "university_id": "imperial-computing-msc",
        "university_name": "Imperial College London",
        "country": "UK",
        "degree_level": "Masters",
        "program_name": "MSc Computing",
        "admissions_url": "https://www.imperial.ac.uk/study/apply/postgraduate-taught/",
    },
    {
        "university_id": "imperial-ai-msc",
        "university_name": "Imperial College London",
        "country": "UK",
        "degree_level": "Masters",
        "program_name": "MSc AI",
        "admissions_url": "https://www.imperial.ac.uk/study/apply/postgraduate-taught/",
    },
    {
        "university_id": "cambridge-cs-phd",
        "university_name": "University of Cambridge",
        "country": "UK",
        "degree_level": "PhD",
        "program_name": "PhD Computer Science",
        "admissions_url": "https://www.postgraduate.study.cam.ac.uk/courses/directory",
    },
    {
        "university_id": "oxford-cs-msc",
        "university_name": "University of Oxford",
        "country": "UK",
        "degree_level": "Masters",
        "program_name": "MSc Computer Science",
        "admissions_url": "https://www.ox.ac.uk/admissions/graduate",
    },
    {
        "university_id": "oxford-cs-dphil",
        "university_name": "University of Oxford",
        "country": "UK",
        "degree_level": "PhD",
        "program_name": "DPhil Computer Science",
        "admissions_url": "https://www.ox.ac.uk/admissions/graduate",
    },
    {
        "university_id": "kings-ai-msc",
        "university_name": "Kings College London",
        "country": "UK",
        "degree_level": "Masters",
        "program_name": "MSc AI",
        "admissions_url": "https://www.kcl.ac.uk/study/postgraduate-taught",
    },
    {
        "university_id": "bristol-ds-msc",
        "university_name": "University of Bristol",
        "country": "UK",
        "degree_level": "Masters",
        "program_name": "MSc Data Science",
        "admissions_url": "https://www.bristol.ac.uk/study/postgraduate/",
    },
    {
        "university_id": "warwick-cs-msc",
        "university_name": "University of Warwick",
        "country": "UK",
        "degree_level": "Masters",
        "program_name": "MSc Computer Science",
        "admissions_url": "https://warwick.ac.uk/study/postgraduate/",
    },
    # France
    {
        "university_id": "ecole-polytechnique-ds-msc",
        "university_name": "Ecole Polytechnique",
        "country": "France",
        "degree_level": "Masters",
        "program_name": "MSc Data Science",
        "admissions_url": "https://www.polytechnique.edu/en/education",
    },
    {
        "university_id": "ecole-polytechnique-ai-phd",
        "university_name": "Ecole Polytechnique",
        "country": "France",
        "degree_level": "PhD",
        "program_name": "PhD AI",
        "admissions_url": "https://www.polytechnique.edu/en/education/phd",
    },
    {
        "university_id": "sorbonne-cs-msc",
        "university_name": "Sorbonne University",
        "country": "France",
        "degree_level": "Masters",
        "program_name": "MSc Computer Science",
        "admissions_url": "https://www.sorbonne-universite.fr/en/education",
    },
    {
        "university_id": "paris-saclay-ai-msc",
        "university_name": "Paris-Saclay University",
        "country": "France",
        "degree_level": "Masters",
        "program_name": "MSc AI",
        "admissions_url": "https://www.universite-paris-saclay.fr/en/education",
    },
    {
        "university_id": "centralesupelec-ai-msc",
        "university_name": "CentraleSupelec",
        "country": "France",
        "degree_level": "Masters",
        "program_name": "MSc AI",
        "admissions_url": "https://www.centralesupelec.fr/en/education",
    },
    # Taiwan
    {
        "university_id": "ntu-taiwan-cs-msc",
        "university_name": "National Taiwan University (NTU)",
        "country": "Taiwan",
        "degree_level": "Masters",
        "program_name": "MSc Computer Science",
        "admissions_url": "https://www.ntu.edu.tw/english/",
    },
    {
        "university_id": "ntu-taiwan-ai-msc",
        "university_name": "National Taiwan University (NTU)",
        "country": "Taiwan",
        "degree_level": "Masters",
        "program_name": "MSc AI",
        "admissions_url": "https://www.ntu.edu.tw/english/",
    },
    {
        "university_id": "ntu-taiwan-cs-phd",
        "university_name": "National Taiwan University (NTU)",
        "country": "Taiwan",
        "degree_level": "PhD",
        "program_name": "PhD CS",
        "admissions_url": "https://www.ntu.edu.tw/english/",
    },
    {
        "university_id": "ncku-cs-msc",
        "university_name": "National Cheng Kung University",
        "country": "Taiwan",
        "degree_level": "Masters",
        "program_name": "MSc Computer Science",
        "admissions_url": "https://web.ncku.edu.tw/p/412-1000-42.php?Lang=en",
    },
    {
        "university_id": "nthu-ai-msc",
        "university_name": "National Tsing Hua University",
        "country": "Taiwan",
        "degree_level": "Masters",
        "program_name": "MSc AI",
        "admissions_url": "https://oga.nthu.edu.tw/en/",
    },
    {
        "university_id": "nycu-ds-msc",
        "university_name": "National Yang Ming Chiao Tung University",
        "country": "Taiwan",
        "degree_level": "Masters",
        "program_name": "MSc Data Science",
        "admissions_url": "https://en.nycu.edu.tw/",
    },
    {
        "university_id": "academia-sinica-cs-phd",
        "university_name": "Academia Sinica",
        "country": "Taiwan",
        "degree_level": "PhD",
        "program_name": "PhD Computer Science",
        "admissions_url": "https://www.sinica.edu.tw/en",
    },
    # South Korea
    {
        "university_id": "yonsei-cs-msc",
        "university_name": "Yonsei University",
        "country": "South Korea",
        "degree_level": "Masters",
        "program_name": "MSc Computer Science",
        "admissions_url": "https://www.yonsei.ac.kr/en_sc/",
    },
    {
        "university_id": "korea-ai-msc",
        "university_name": "Korea University",
        "country": "South Korea",
        "degree_level": "Masters",
        "program_name": "MSc AI",
        "admissions_url": "https://www.korea.ac.kr/mbshome/mbs/en/index.do",
    },
    {
        "university_id": "skku-cs-msc",
        "university_name": "Sungkyunkwan University (SKKU)",
        "country": "South Korea",
        "degree_level": "Masters",
        "program_name": "MSc Computer Science",
        "admissions_url": "https://www.skku.edu/eng/",
    },
    {
        "university_id": "hanyang-ds-msc",
        "university_name": "Hanyang University",
        "country": "South Korea",
        "degree_level": "Masters",
        "program_name": "MSc Data Science",
        "admissions_url": "https://www.hanyang.ac.kr/web/eng",
    },
    # Japan
    {
        "university_id": "tokyo-tech-cs-msc",
        "university_name": "Tokyo Institute of Technology",
        "country": "Japan",
        "degree_level": "Masters",
        "program_name": "MSc Computer Science",
        "admissions_url": "https://www.titech.ac.jp/english/graduate_school",
    },
    {
        "university_id": "tokyo-tech-ai-msc",
        "university_name": "Tokyo Institute of Technology",
        "country": "Japan",
        "degree_level": "Masters",
        "program_name": "MSc AI",
        "admissions_url": "https://www.titech.ac.jp/english/graduate_school",
    },
    {
        "university_id": "tohoku-ai-msc",
        "university_name": "Tohoku University",
        "country": "Japan",
        "degree_level": "Masters",
        "program_name": "MSc AI",
        "admissions_url": "https://www.tohoku.ac.jp/en/admissions/",
    },
    {
        "university_id": "nagoya-cs-msc",
        "university_name": "Nagoya University",
        "country": "Japan",
        "degree_level": "Masters",
        "program_name": "MSc Computer Science",
        "admissions_url": "https://en.nagoya-u.ac.jp/admissions/",
    },
    {
        "university_id": "kyushu-ds-msc",
        "university_name": "Kyushu University",
        "country": "Japan",
        "degree_level": "Masters",
        "program_name": "MSc Data Science",
        "admissions_url": "https://www.kyushu-u.ac.jp/en/admission/",
    },
    {
        "university_id": "keio-cs-msc",
        "university_name": "Keio University",
        "country": "Japan",
        "degree_level": "Masters",
        "program_name": "MSc Computer Science",
        "admissions_url": "https://www.keio.ac.jp/en/admissions/",
    },
    # China
    {
        "university_id": "tsinghua-ai-msc",
        "university_name": "Tsinghua University",
        "country": "China",
        "degree_level": "Masters",
        "program_name": "MSc AI",
        "admissions_url": "https://www.tsinghua.edu.cn/en/Admissions.htm",
    },
    {
        "university_id": "tsinghua-cs-phd",
        "university_name": "Tsinghua University",
        "country": "China",
        "degree_level": "PhD",
        "program_name": "PhD Computer Science",
        "admissions_url": "https://www.tsinghua.edu.cn/en/Admissions.htm",
    },
    {
        "university_id": "peking-cs-msc",
        "university_name": "Peking University",
        "country": "China",
        "degree_level": "Masters",
        "program_name": "MSc Computer Science",
        "admissions_url": "https://english.pku.edu.cn/Admissions/",
    },
    {
        "university_id": "fudan-ds-msc",
        "university_name": "Fudan University",
        "country": "China",
        "degree_level": "Masters",
        "program_name": "MSc Data Science",
        "admissions_url": "https://iso.fudan.edu.cn/isoenglish/",
    },
    {
        "university_id": "sjtu-cs-msc",
        "university_name": "Shanghai Jiao Tong University",
        "country": "China",
        "degree_level": "Masters",
        "program_name": "MSc Computer Science",
        "admissions_url": "https://en.sjtu.edu.cn/admissions",
    },
    {
        "university_id": "sjtu-ai-msc",
        "university_name": "Shanghai Jiao Tong University",
        "country": "China",
        "degree_level": "Masters",
        "program_name": "MSc AI",
        "admissions_url": "https://en.sjtu.edu.cn/admissions",
    },
    {
        "university_id": "wuhan-cs-msc",
        "university_name": "Wuhan University",
        "country": "China",
        "degree_level": "Masters",
        "program_name": "MSc Computer Science",
        "admissions_url": "https://admission.whu.edu.cn/",
    },
    {
        "university_id": "sysu-ai-msc",
        "university_name": "Sun Yat-sen University",
        "country": "China",
        "degree_level": "Masters",
        "program_name": "MSc AI",
        "admissions_url": "https://admissions.sysu.edu.cn/",
    },
    # India
    {
        "university_id": "iit-delhi-ai-msc",
        "university_name": "IIT Delhi",
        "country": "India",
        "degree_level": "Masters",
        "program_name": "MSc AI",
        "admissions_url": "https://home.iitd.ac.in/",
    },
    {
        "university_id": "iit-delhi-cs-mtech",
        "university_name": "IIT Delhi",
        "country": "India",
        "degree_level": "Masters",
        "program_name": "MTech Computer Science",
        "admissions_url": "https://home.iitd.ac.in/",
    },
    {
        "university_id": "iit-bombay-cs-mtech",
        "university_name": "IIT Bombay",
        "country": "India",
        "degree_level": "Masters",
        "program_name": "MTech Computer Science",
        "admissions_url": "https://www.iitb.ac.in/",
    },
    {
        "university_id": "iit-bombay-cs-phd",
        "university_name": "IIT Bombay",
        "country": "India",
        "degree_level": "PhD",
        "program_name": "PhD Computer Science",
        "admissions_url": "https://www.iitb.ac.in/",
    },
    {
        "university_id": "iit-madras-ds-msc",
        "university_name": "IIT Madras",
        "country": "India",
        "degree_level": "Masters",
        "program_name": "MSc Data Science",
        "admissions_url": "https://www.iitm.ac.in/",
    },
    {
        "university_id": "iisc-ai-msc",
        "university_name": "IISC Bangalore",
        "country": "India",
        "degree_level": "Masters",
        "program_name": "MSc AI",
        "admissions_url": "https://iisc.ac.in/admissions/",
    },
    {
        "university_id": "iisc-cs-phd",
        "university_name": "IISC Bangalore",
        "country": "India",
        "degree_level": "PhD",
        "program_name": "PhD Computer Science",
        "admissions_url": "https://iisc.ac.in/admissions/",
    },
    {
        "university_id": "iit-kharagpur-cs-mtech",
        "university_name": "IIT Kharagpur",
        "country": "India",
        "degree_level": "Masters",
        "program_name": "MTech Computer Science",
        "admissions_url": "https://www.iitkgp.ac.in/",
    },
    # Indonesia, Thailand, Vietnam
    {
        "university_id": "itb-cs-msc",
        "university_name": "Institut Teknologi Bandung (ITB)",
        "country": "Indonesia",
        "degree_level": "Masters",
        "program_name": "MSc Computer Science",
        "admissions_url": "https://www.itb.ac.id/admission",
    },
    {
        "university_id": "ait-cs-msc",
        "university_name": "Asian Institute of Technology (AIT)",
        "country": "Thailand",
        "degree_level": "Masters",
        "program_name": "MSc Computer Science",
        "admissions_url": "https://ait.ac.th/admissions/",
    },
    {
        "university_id": "ait-ai-msc",
        "university_name": "Asian Institute of Technology (AIT)",
        "country": "Thailand",
        "degree_level": "Masters",
        "program_name": "MSc AI",
        "admissions_url": "https://ait.ac.th/admissions/",
    },
    {
        "university_id": "vnu-cs-msc",
        "university_name": "Vietnam National University",
        "country": "Vietnam",
        "degree_level": "Masters",
        "program_name": "MSc Computer Science",
        "admissions_url": "https://en.vnu.edu.vn/",
    },
    # Middle East
    {
        "university_id": "kaust-cs-ms",
        "university_name": "King Abdullah University of Science and Technology (KAUST)",
        "country": "Saudi Arabia",
        "degree_level": "Masters",
        "program_name": "MS Computer Science",
        "admissions_url": "https://www.kaust.edu.sa/en/study",
    },
    {
        "university_id": "kaust-ai-phd",
        "university_name": "King Abdullah University of Science and Technology (KAUST)",
        "country": "Saudi Arabia",
        "degree_level": "PhD",
        "program_name": "PhD AI",
        "admissions_url": "https://www.kaust.edu.sa/en/study",
    },
    {
        "university_id": "kfupm-cs-ms",
        "university_name": "King Fahd University of Petroleum and Minerals (KFUPM)",
        "country": "Saudi Arabia",
        "degree_level": "Masters",
        "program_name": "MS Computer Science",
        "admissions_url": "https://www.kfupm.edu.sa/",
    },
    {
        "university_id": "uaeu-cs-ms",
        "university_name": "United Arab Emirates University",
        "country": "United Arab Emirates",
        "degree_level": "Masters",
        "program_name": "MS Computer Science",
        "admissions_url": "https://www.uaeu.ac.ae/en/admission.shtml",
    },
    {
        "university_id": "khalifa-ai-ms",
        "university_name": "Khalifa University",
        "country": "United Arab Emirates",
        "degree_level": "Masters",
        "program_name": "MS AI",
        "admissions_url": "https://www.ku.ac.ae/admissions/",
    },
    {
        "university_id": "qatar-cs-ms",
        "university_name": "Qatar University",
        "country": "Qatar",
        "degree_level": "Masters",
        "program_name": "MS Computer Science",
        "admissions_url": "https://www.qu.edu.qa/students/admission",
    },
    {
        "university_id": "aub-cs-ms",
        "university_name": "American University of Beirut",
        "country": "Lebanon",
        "degree_level": "Masters",
        "program_name": "MS Computer Science",
        "admissions_url": "https://www.aub.edu.lb/admissions/",
    },
    # Central Asia
    {
        "university_id": "nazarbayev-cs-ms",
        "university_name": "Nazarbayev University",
        "country": "Kazakhstan",
        "degree_level": "Masters",
        "program_name": "MS Computer Science",
        "admissions_url": "https://nu.edu.kz/admissions",
    },
    {
        "university_id": "university-central-asia-it-ms",
        "university_name": "University of Central Asia",
        "country": "Kazakhstan",
        "degree_level": "Masters",
        "program_name": "MS Information Technology",
        "admissions_url": "https://ucentralasia.org/admissions",
    },
    # Australia and New Zealand
    {
        "university_id": "uq-cs-msc",
        "university_name": "University of Queensland",
        "country": "Australia",
        "degree_level": "Masters",
        "program_name": "MS Computer Science",
        "admissions_url": "https://study.uq.edu.au/study-options",
    },
    {
        "university_id": "uq-ai-msc",
        "university_name": "University of Queensland",
        "country": "Australia",
        "degree_level": "Masters",
        "program_name": "MS AI",
        "admissions_url": "https://study.uq.edu.au/study-options",
    },
    {
        "university_id": "monash-ds-msc",
        "university_name": "Monash University",
        "country": "Australia",
        "degree_level": "Masters",
        "program_name": "MS Data Science",
        "admissions_url": "https://www.monash.edu/study/courses",
    },
    {
        "university_id": "monash-ai-msc",
        "university_name": "Monash University",
        "country": "Australia",
        "degree_level": "Masters",
        "program_name": "MS AI",
        "admissions_url": "https://www.monash.edu/study/courses",
    },
    {
        "university_id": "unsw-cs-msc",
        "university_name": "University of New South Wales (UNSW)",
        "country": "Australia",
        "degree_level": "Masters",
        "program_name": "MS Computer Science",
        "admissions_url": "https://www.unsw.edu.au/study",
    },
    {
        "university_id": "macquarie-ds-msc",
        "university_name": "Macquarie University",
        "country": "Australia",
        "degree_level": "Masters",
        "program_name": "MS Data Science",
        "admissions_url": "https://www.mq.edu.au/study",
    },
    # USA
    {
        "university_id": "berkeley-cs-phd",
        "university_name": "University of California Berkeley",
        "country": "USA",
        "degree_level": "PhD",
        "program_name": "PhD Computer Science",
        "admissions_url": "https://grad.berkeley.edu/admissions/",
    },
    {
        "university_id": "uiuc-cs-ms",
        "university_name": "University of Illinois Urbana-Champaign (UIUC)",
        "country": "USA",
        "degree_level": "Masters",
        "program_name": "MS Computer Science",
        "admissions_url": "https://cs.illinois.edu/admissions/graduate",
    },
    {
        "university_id": "uiuc-ai-phd",
        "university_name": "University of Illinois Urbana-Champaign (UIUC)",
        "country": "USA",
        "degree_level": "PhD",
        "program_name": "PhD AI",
        "admissions_url": "https://cs.illinois.edu/admissions/graduate",
    },
    {
        "university_id": "gatech-cs-ms",
        "university_name": "Georgia Tech",
        "country": "USA",
        "degree_level": "Masters",
        "program_name": "MS Computer Science",
        "admissions_url": "https://www.cc.gatech.edu/academics/degree-programs",
    },
    {
        "university_id": "gatech-ai-msc",
        "university_name": "Georgia Tech",
        "country": "USA",
        "degree_level": "Masters",
        "program_name": "MS AI",
        "admissions_url": "https://www.cc.gatech.edu/academics/degree-programs",
    },
    {
        "university_id": "washington-cs-ms",
        "university_name": "University of Washington",
        "country": "USA",
        "degree_level": "Masters",
        "program_name": "MS Computer Science",
        "admissions_url": "https://www.cs.washington.edu/academics/grad/admissions",
    },
    {
        "university_id": "washington-ai-phd",
        "university_name": "University of Washington",
        "country": "USA",
        "degree_level": "PhD",
        "program_name": "PhD AI",
        "admissions_url": "https://www.cs.washington.edu/academics/grad/admissions",
    },
    {
        "university_id": "columbia-cs-msc",
        "university_name": "Columbia University",
        "country": "USA",
        "degree_level": "Masters",
        "program_name": "MS Computer Science",
        "admissions_url": "https://www.engineering.columbia.edu/admissions",
    },
    {
        "university_id": "cornell-cs-msc",
        "university_name": "Cornell University",
        "country": "USA",
        "degree_level": "Masters",
        "program_name": "MS Computer Science",
        "admissions_url": "https://www.cs.cornell.edu/masters-program",
    },
    {
        "university_id": "cornell-ai-phd",
        "university_name": "Cornell University",
        "country": "USA",
        "degree_level": "PhD",
        "program_name": "PhD AI",
        "admissions_url": "https://www.cs.cornell.edu/phd",
    },
    # Canada
    {
        "university_id": "ubc-cs-msc",
        "university_name": "University of British Columbia (UBC)",
        "country": "Canada",
        "degree_level": "Masters",
        "program_name": "MS Computer Science",
        "admissions_url": "https://www.cs.ubc.ca/students/graduate",
    },
    {
        "university_id": "mcgill-cs-msc",
        "university_name": "McGill University",
        "country": "Canada",
        "degree_level": "Masters",
        "program_name": "MS Computer Science",
        "admissions_url": "https://www.mcgill.ca/gradapplicants/apply",
    },
    {
        "university_id": "mcgill-ai-phd",
        "university_name": "McGill University",
        "country": "Canada",
        "degree_level": "PhD",
        "program_name": "PhD AI",
        "admissions_url": "https://www.mcgill.ca/gradapplicants/apply",
    },
    {
        "university_id": "waterloo-cs-msc",
        "university_name": "University of Waterloo",
        "country": "Canada",
        "degree_level": "Masters",
        "program_name": "MS Computer Science",
        "admissions_url": "https://uwaterloo.ca/future-graduate-students/programs",
    },
    {
        "university_id": "waterloo-ai-msc",
        "university_name": "University of Waterloo",
        "country": "Canada",
        "degree_level": "Masters",
        "program_name": "MS AI",
        "admissions_url": "https://uwaterloo.ca/future-graduate-students/programs",
    },
    {
        "university_id": "york-cs-msc",
        "university_name": "York University",
        "country": "Canada",
        "degree_level": "Masters",
        "program_name": "MS Computer Science",
        "admissions_url": "https://www.yorku.ca/graduate/future-students/how-to-apply/",
    },
    # Extra bachelors for major universities
    {
        "university_id": "ku-leuven-cs-bsc",
        "university_name": "KU Leuven",
        "country": "Belgium",
        "degree_level": "Bachelors",
        "program_name": "BSc Computer Science",
        "admissions_url": "https://www.kuleuven.be/english/study/bachelors",
    },
    {
        "university_id": "tudelft-cs-bsc",
        "university_name": "Delft University of Technology (TU Delft)",
        "country": "Netherlands",
        "degree_level": "Bachelors",
        "program_name": "BSc Computer Science",
        "admissions_url": "https://www.tudelft.nl/en/education/programmes/bachelors",
    },
    {
        "university_id": "imperial-cs-bsc",
        "university_name": "Imperial College London",
        "country": "UK",
        "degree_level": "Bachelors",
        "program_name": "BSc Computing",
        "admissions_url": "https://www.imperial.ac.uk/study/apply/undergraduate/",
    },
    {
        "university_id": "berkeley-cs-bs",
        "university_name": "University of California Berkeley",
        "country": "USA",
        "degree_level": "Bachelors",
        "program_name": "BS Computer Science",
        "admissions_url": "https://admissions.berkeley.edu/apply-now/",
    },
    {
        "university_id": "waterloo-cs-bcs",
        "university_name": "University of Waterloo",
        "country": "Canada",
        "degree_level": "Bachelors",
        "program_name": "BCS Computer Science",
        "admissions_url": "https://uwaterloo.ca/future-students/admissions",
    },
    {
        "university_id": "nus-cs-bsc",
        "university_name": "National University of Singapore (NUS)",
        "country": "Singapore",
        "degree_level": "Bachelors",
        "program_name": "BComp Computer Science",
        "admissions_url": "https://www.nus.edu.sg/oam/undergraduate-programmes",
    },
    {
        "university_id": "ntu-cs-bsc",
        "university_name": "Nanyang Technological University (NTU)",
        "country": "Singapore",
        "degree_level": "Bachelors",
        "program_name": "BSc Computer Science",
        "admissions_url": "https://www.ntu.edu.sg/admissions/undergraduate",
    },
]


ADDITIONAL_SEED_TARGETS.extend(MORE_SEED_TARGETS)


COUNTRY_FALLBACK_RULES: dict[str, dict[str, Any]] = {
    "China": {
        "application_deadline_start": "2026-03-01",
        "application_deadline_end": "2026-06-30",
        "application_fee_required": False,
        "application_fee_amount": 0,
        "application_fee_currency": "CNY",
        "scholarship_available": True,
        "scholarship_details": "Chinese Government Scholarship and university scholarships may be available for outstanding international students.",
    },
    "Malaysia": {
        "application_deadline_start": "2026-04-01",
        "application_deadline_end": "2026-08-31",
        "application_fee_required": True,
        "application_fee_amount": 200,
        "application_fee_currency": "MYR",
        "scholarship_available": True,
        "scholarship_details": "Merit scholarships and partial tuition waivers are commonly offered for strong applicants.",
    },
    "Czech Republic": {
        "application_deadline_start": "2026-01-15",
        "application_deadline_end": "2026-04-30",
        "application_fee_required": False,
        "application_fee_amount": 0,
        "application_fee_currency": "CZK",
        "scholarship_available": False,
        "scholarship_details": None,
    },
    "Hungary": {
        "application_deadline_start": "2026-01-15",
        "application_deadline_end": "2026-03-31",
        "application_fee_required": True,
        "application_fee_amount": 75,
        "application_fee_currency": "EUR",
        "scholarship_available": True,
        "scholarship_details": "Stipendium Hungaricum and university scholarships are widely available for international students.",
    },
    "Italy": {
        "application_deadline_start": "2026-03-01",
        "application_deadline_end": "2026-07-31",
        "application_fee_required": False,
        "application_fee_amount": 0,
        "application_fee_currency": "EUR",
        "scholarship_available": True,
        "scholarship_details": "Need-based tuition reductions, regional scholarships, and merit awards may be available.",
    },
    "Netherlands": {
        "application_deadline_start": "2026-01-15",
        "application_deadline_end": "2026-04-15",
        "application_fee_required": True,
        "application_fee_amount": 100,
        "application_fee_currency": "EUR",
        "scholarship_available": True,
        "scholarship_details": "Some universities offer merit scholarships and tuition waivers for top international candidates.",
    },
    "Sweden": {
        "application_deadline_start": "2026-10-01",
        "application_deadline_end": "2027-01-15",
        "application_fee_required": True,
        "application_fee_amount": 900,
        "application_fee_currency": "SEK",
        "scholarship_available": True,
        "scholarship_details": "Swedish Institute and university scholarships are common for outstanding international students.",
    },
    "Norway": {
        "application_deadline_start": "2026-12-01",
        "application_deadline_end": "2027-03-01",
        "application_fee_required": False,
        "application_fee_amount": 0,
        "application_fee_currency": "NOK",
        "scholarship_available": False,
        "scholarship_details": None,
    },
    "Finland": {
        "application_deadline_start": "2026-12-01",
        "application_deadline_end": "2027-01-15",
        "application_fee_required": True,
        "application_fee_amount": 100,
        "application_fee_currency": "EUR",
        "scholarship_available": True,
        "scholarship_details": "Fee waivers and scholarship packages are often available for excellent applicants.",
    },
    "Austria": {
        "application_deadline_start": "2026-03-01",
        "application_deadline_end": "2026-05-31",
        "application_fee_required": False,
        "application_fee_amount": 0,
        "application_fee_currency": "EUR",
        "scholarship_available": False,
        "scholarship_details": None,
    },
    "Spain": {
        "application_deadline_start": "2026-04-01",
        "application_deadline_end": "2026-06-30",
        "application_fee_required": True,
        "application_fee_amount": 60,
        "application_fee_currency": "EUR",
        "scholarship_available": False,
        "scholarship_details": None,
    },
    "USA": {
        "application_deadline_start": "2026-09-01",
        "application_deadline_end": "2026-12-15",
        "application_fee_required": True,
        "application_fee_amount": 100,
        "application_fee_currency": "USD",
        "scholarship_available": True,
        "scholarship_details": "PhD and strong master's applicants may receive funding, fellowships, or assistantships.",
    },
    "Australia": {
        "application_deadline_start": "2026-02-01",
        "application_deadline_end": "2026-10-31",
        "application_fee_required": True,
        "application_fee_amount": 125,
        "application_fee_currency": "AUD",
        "scholarship_available": True,
        "scholarship_details": "Merit scholarships and research stipends are common for strong applicants.",
    },
    "New Zealand": {
        "application_deadline_start": "2026-07-01",
        "application_deadline_end": "2026-11-30",
        "application_fee_required": True,
        "application_fee_amount": 50,
        "application_fee_currency": "NZD",
        "scholarship_available": True,
        "scholarship_details": "University scholarships and tuition awards may be offered to international students.",
    },
    "South Korea": {
        "application_deadline_start": "2026-02-01",
        "application_deadline_end": "2026-04-30",
        "application_fee_required": True,
        "application_fee_amount": 100000,
        "application_fee_currency": "KRW",
        "scholarship_available": True,
        "scholarship_details": "KAIST-style tuition waivers and graduate scholarships are common at research universities.",
    },
    "Japan": {
        "application_deadline_start": "2026-11-01",
        "application_deadline_end": "2027-02-28",
        "application_fee_required": True,
        "application_fee_amount": 30000,
        "application_fee_currency": "JPY",
        "scholarship_available": True,
        "scholarship_details": "MEXT-style scholarships, university fee waivers, and lab funding may be available.",
    },
    "Singapore": {
        "application_deadline_start": "2026-08-01",
        "application_deadline_end": "2026-11-30",
        "application_fee_required": True,
        "application_fee_amount": 50,
        "application_fee_currency": "SGD",
        "scholarship_available": True,
        "scholarship_details": "Research scholarships and tuition grants are often available for outstanding graduate applicants.",
    },
}


MORE_COUNTRY_FALLBACK_RULES: dict[str, dict[str, Any]] = {
    "Portugal": {
        "application_deadline_start": "2026-01-15",
        "application_deadline_end": "2026-05-31",
        "application_fee_required": True,
        "application_fee_amount": 55,
        "application_fee_currency": "EUR",
        "scholarship_available": True,
        "scholarship_details": "University merit awards and some national scholarships may be available for international students.",
    },
    "Belgium": {
        "application_deadline_start": "2026-02-01",
        "application_deadline_end": "2026-06-30",
        "application_fee_required": True,
        "application_fee_amount": 90,
        "application_fee_currency": "EUR",
        "scholarship_available": True,
        "scholarship_details": "Belgian university scholarships and tuition reductions may be available for strong applicants.",
    },
    "Switzerland": {
        "application_deadline_start": "2026-11-01",
        "application_deadline_end": "2027-02-28",
        "application_fee_required": True,
        "application_fee_amount": 100,
        "application_fee_currency": "CHF",
        "scholarship_available": True,
        "scholarship_details": "Swiss government and university scholarships may be available for excellent international students.",
    },
    "Denmark": {
        "application_deadline_start": "2026-11-01",
        "application_deadline_end": "2027-03-15",
        "application_fee_required": True,
        "application_fee_amount": 750,
        "application_fee_currency": "DKK",
        "scholarship_available": True,
        "scholarship_details": "Danish government and university scholarships may be available for non-EU applicants.",
    },
    "Ireland": {
        "application_deadline_start": "2026-01-15",
        "application_deadline_end": "2026-06-30",
        "application_fee_required": True,
        "application_fee_amount": 50,
        "application_fee_currency": "EUR",
        "scholarship_available": True,
        "scholarship_details": "Irish university scholarships and fee waivers may be available for international students.",
    },
    "Poland": {
        "application_deadline_start": "2026-03-01",
        "application_deadline_end": "2026-07-31",
        "application_fee_required": True,
        "application_fee_amount": 85,
        "application_fee_currency": "PLN",
        "scholarship_available": True,
        "scholarship_details": "Polish government and university scholarships may be available for strong candidates.",
    },
    "Greece": {
        "application_deadline_start": "2026-05-01",
        "application_deadline_end": "2026-08-31",
        "application_fee_required": False,
        "application_fee_amount": 0,
        "application_fee_currency": "EUR",
        "scholarship_available": True,
        "scholarship_details": "Some Greek universities offer reduced tuition or merit support for international students.",
    },
    "Estonia": {
        "application_deadline_start": "2026-01-15",
        "application_deadline_end": "2026-04-30",
        "application_fee_required": True,
        "application_fee_amount": 100,
        "application_fee_currency": "EUR",
        "scholarship_available": True,
        "scholarship_details": "Estonian universities often offer tuition waivers and scholarships for international applicants.",
    },
    "Latvia": {
        "application_deadline_start": "2026-03-01",
        "application_deadline_end": "2026-07-31",
        "application_fee_required": True,
        "application_fee_amount": 150,
        "application_fee_currency": "EUR",
        "scholarship_available": True,
        "scholarship_details": "Latvian university scholarships may be available for outstanding international students.",
    },
    "Lithuania": {
        "application_deadline_start": "2026-03-01",
        "application_deadline_end": "2026-07-31",
        "application_fee_required": True,
        "application_fee_amount": 100,
        "application_fee_currency": "EUR",
        "scholarship_available": True,
        "scholarship_details": "Lithuanian universities may offer fee reductions and scholarships for top applicants.",
    },
    "Romania": {
        "application_deadline_start": "2026-04-01",
        "application_deadline_end": "2026-08-15",
        "application_fee_required": True,
        "application_fee_amount": 50,
        "application_fee_currency": "EUR",
        "scholarship_available": True,
        "scholarship_details": "Romanian government and university scholarships may be available for international students.",
    },
    "Serbia": {
        "application_deadline_start": "2026-05-01",
        "application_deadline_end": "2026-08-31",
        "application_fee_required": False,
        "application_fee_amount": 0,
        "application_fee_currency": "EUR",
        "scholarship_available": False,
        "scholarship_details": None,
    },
    "Croatia": {
        "application_deadline_start": "2026-04-01",
        "application_deadline_end": "2026-07-31",
        "application_fee_required": False,
        "application_fee_amount": 0,
        "application_fee_currency": "EUR",
        "scholarship_available": False,
        "scholarship_details": None,
    },
    "Slovakia": {
        "application_deadline_start": "2026-02-01",
        "application_deadline_end": "2026-06-30",
        "application_fee_required": False,
        "application_fee_amount": 0,
        "application_fee_currency": "EUR",
        "scholarship_available": True,
        "scholarship_details": "Slovak scholarships and fee waivers may be available for international students.",
    },
    "France": {
        "application_deadline_start": "2026-01-15",
        "application_deadline_end": "2026-05-31",
        "application_fee_required": True,
        "application_fee_amount": 100,
        "application_fee_currency": "EUR",
        "scholarship_available": True,
        "scholarship_details": "French government and university scholarships are commonly available for strong applicants.",
    },
    "Taiwan": {
        "application_deadline_start": "2026-02-01",
        "application_deadline_end": "2026-04-30",
        "application_fee_required": True,
        "application_fee_amount": 60,
        "application_fee_currency": "USD",
        "scholarship_available": True,
        "scholarship_details": "Taiwan scholarship programs and university funding are often available for international students.",
    },
    "India": {
        "application_deadline_start": "2026-03-01",
        "application_deadline_end": "2026-06-30",
        "application_fee_required": True,
        "application_fee_amount": 1500,
        "application_fee_currency": "INR",
        "scholarship_available": True,
        "scholarship_details": "Institute scholarships, assistantships, and fellowships may be available for research students.",
    },
    "Indonesia": {
        "application_deadline_start": "2026-03-01",
        "application_deadline_end": "2026-07-31",
        "application_fee_required": True,
        "application_fee_amount": 500000,
        "application_fee_currency": "IDR",
        "scholarship_available": True,
        "scholarship_details": "Indonesian university scholarships and tuition reductions may be available for international students.",
    },
    "Thailand": {
        "application_deadline_start": "2026-04-01",
        "application_deadline_end": "2026-08-31",
        "application_fee_required": True,
        "application_fee_amount": 1000,
        "application_fee_currency": "THB",
        "scholarship_available": True,
        "scholarship_details": "Thai universities often offer scholarships and assistantships for graduate students.",
    },
    "Vietnam": {
        "application_deadline_start": "2026-03-01",
        "application_deadline_end": "2026-07-31",
        "application_fee_required": True,
        "application_fee_amount": 30,
        "application_fee_currency": "USD",
        "scholarship_available": True,
        "scholarship_details": "Vietnamese universities may provide tuition support and scholarships for international students.",
    },
    "Saudi Arabia": {
        "application_deadline_start": "2026-01-01",
        "application_deadline_end": "2026-04-30",
        "application_fee_required": False,
        "application_fee_amount": 0,
        "application_fee_currency": "SAR",
        "scholarship_available": True,
        "scholarship_details": "Full scholarships and stipends are common at major Saudi research universities.",
    },
    "United Arab Emirates": {
        "application_deadline_start": "2026-02-01",
        "application_deadline_end": "2026-06-30",
        "application_fee_required": True,
        "application_fee_amount": 100,
        "application_fee_currency": "AED",
        "scholarship_available": True,
        "scholarship_details": "Scholarships and fee waivers may be available for high-achieving graduate applicants.",
    },
    "Qatar": {
        "application_deadline_start": "2026-02-01",
        "application_deadline_end": "2026-06-30",
        "application_fee_required": True,
        "application_fee_amount": 100,
        "application_fee_currency": "QAR",
        "scholarship_available": True,
        "scholarship_details": "Qatar University and national scholarships may be available for international students.",
    },
    "Lebanon": {
        "application_deadline_start": "2026-03-01",
        "application_deadline_end": "2026-06-30",
        "application_fee_required": True,
        "application_fee_amount": 50,
        "application_fee_currency": "USD",
        "scholarship_available": True,
        "scholarship_details": "Some universities offer merit aid and financial assistance for graduate students.",
    },
    "Kazakhstan": {
        "application_deadline_start": "2026-02-01",
        "application_deadline_end": "2026-05-31",
        "application_fee_required": False,
        "application_fee_amount": 0,
        "application_fee_currency": "KZT",
        "scholarship_available": True,
        "scholarship_details": "Scholarships and fully funded graduate programs are commonly available at leading Kazakh universities.",
    },
}


COUNTRY_FALLBACK_RULES.update(MORE_COUNTRY_FALLBACK_RULES)
